### ISSUE TITLE
Segfault attempting to run wcc on libvivoxsdk.so

### ISSUE THREAD

**Issue by no-boot-device** [endrazine/wcc#13]
Attempting to run wcc on libvivoxsdk.so causes a segfault for me.
Here are the last few lines in debug mode:
```
--> transforming relocation from section: .gnu.hash at 0x195f39:	cmp	eax, 0xff	inslen:3  argoffset:4294967295
new local sindex:1 addent:43, off:0x10000d478	hasrel:0
[1]    23189 segmentation fault (core dumped)  wcc -m i386 -d -s libvivoxsdk.bak -o libvivoxsdk.so
```
Here's a full log:
https://gist.github.com/no-boot-device/d82e50e52f95e00a71ceb41546c6d20e
And here's the full file:
https://drive.google.com/file/d/0BwgL44rRXZ5SNE5uZl84OHJWaEU/view?usp=sharing

It appears to output a file which file recognizes yet has a different hash, and also has seemingly good section headers, but I'm concerned about it segfaulting. (is this just a Thank you for playing Wing Commander! sort of thing?)

**Comment by endrazine** [comment]
Hi :)

The i386 flag isn't recognised as you might have realized, so wcc is really trying to produce a 64b output.

You might want to try like this :
	jonathan@blackbox:/tmp/wtf$ wcc32 libvivoxsdk.bak -o foo.o -c
	jonathan@blackbox:/tmp/wtf$ file foo.o
	foo.o: ELF 32-bit LSB  relocatable, Intel 80386, version 1 (SYSV), not stripped
	jonathan@blackbox:/tmp/wtf$ gcc -m32 foo.o -o foo.so -shared          
	jonathan@blackbox:/tmp/wtf$ file foo.so 
	foo.so: ELF 32-bit LSB  shared object, Intel 80386, version 1 (SYSV), dynamically linked, BuildID[sha1]=80326aa46747ad54bceb31a35b40968042adae8b, not stripped
	jonathan@blackbox:/tmp/wtf$ 

Which seems to work just fine :)

j-
