### ISSUE TITLE
Support for MachO

### ISSUE THREAD

**Issue by samdmarshall** [endrazine/wcc#15]
Just found this project and it is pretty awesome, would be great if it could also support MachO binaries too!

**Comment by nihilus** [comment]
@samdmarshall well in theory it could be done, however MachO is like that cousin with ADHD, a very special kid. It would be nice with a generic solution partly based og libbfd for the purpose.

**Comment by nihilus** [comment]
@samdmarshall I did build it on my OS X machine and fixed some building issues for which I've created a pull request. Among them is a portable 'ldd', for MachO binaries we should have something like a portable version of 'otool'.

**Comment by endrazine** [comment]
Hi samdmarshall,
Thanks for your interrest in WCC. Feel free to extend WCC to better support MachO, we'll be happy to merge your code :)
j-

**Comment by samdmarshall** [comment]
hi @endrazine, could you explain why you marked this issue as closed? Is it because this isn't a goal of the project? typically issues that request enhancements should remain open unless the project owner has no desire to have that implemented and merged.

**Comment by endrazine** [comment]
Hi samdmarshall, thanks for your feature request and your comments. It seems there is nothing else to action at this stage. Feel free to submit your code and request a merge.

**Comment by nihilus** [comment]
@endrazine actuakly this is not in the current scope as it would require to switch from libelf to libbinutils for the toolkit.
