### ISSUE TITLE
Not an issue but a thank you...

### ISSUE THREAD

**Issue by nihilus** [endrazine/wcc#16]
Having had a tool doing exactly the same first time I got stuck with a 3rd part executable being dynamically link to an obsolete libc 10 years ago, I am glad that someone else also recognised this need and actually fixed it.

Ps.
I will fix the linked libraries parsing as relaying on ldd wont do for cross-compilation and such.
Ds.

**Comment by endrazine** [comment]
Thanks nihilus :)
Feel free to commit code !
Cheers,
j-
