### ISSUE TITLE
ls.so: ELF file's phentsize not the expected size

### ISSUE THREAD

**Issue by dakami** [endrazine/wcc#26]
```bash
# wcc -c /bin/ls -s  -o ls.so
# wld -libify ls.so
# python3.6
>>> from ctypes import *
>>> cdll.LoadLibrary("ls.so")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/usr/local/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ls.so: ELF file's phentsize not the expected size
```

Different bug with the other mechanism:

```bash
# wcc -c /bin/ls -o ls.o
# gcc -o ls.so ls.o -shared
>>> cdll.LoadLibrary("ls.so")
python3.6: Symbol `stdout' causes overflow in R_X86_64_PC32 relocation
...
python3.6: Symbol `stderr' causes overflow in R_X86_64_PC32 relocation
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/usr/local/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ls.so: undefined symbol: fgetfilecon
>>> 
```
Not specific to ls.so.  Run on 4.14.13, with various mods.  Happens in a Jessie container, so could be kernel related.

**Comment by dakami** [comment]
Alas, neither Ubuntu 12 or Ubuntu 14 can build wcc anymore.

**Comment by endrazine** [comment]
Hi Dan,

You don't need to use wcc before libifying using wld. See below:

jonathan@blackbox:/tmp/dan$ cp /bin/ls ./ls.so
jonathan@blackbox:/tmp/dan$ wld -libify ./ls.so 
jonathan@blackbox:/tmp/dan$ file ls.so 
ls.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/l, for GNU/Linux 3.2.0, BuildID[sha1]=9567f9a28e66f4d7ec4baf31cfbf68d0410f0ae6, stripped
jonathan@blackbox:/tmp/dan$ python
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from ctypes import *
>>> cdll.LoadLibrary("./ls.so")
<CDLL './ls.so', handle 559cd0aaa9d0 at 7fb3554c7190>
>>> 

It works \o/

**Comment by endrazine** [comment]
Hi Dan,

You don't need to use wcc before libifying using wld. See below:

jonathan@blackbox:/tmp/dan$ cp /bin/ls ./ls.so
jonathan@blackbox:/tmp/dan$ wld -libify ./ls.so 
jonathan@blackbox:/tmp/dan$ file ls.so 
ls.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/l, for GNU/Linux 3.2.0, BuildID[sha1]=9567f9a28e66f4d7ec4baf31cfbf68d0410f0ae6, stripped
jonathan@blackbox:/tmp/dan$ python
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from ctypes import *
>>> cdll.LoadLibrary("./ls.so")
<CDLL './ls.so', handle 559cd0aaa9d0 at 7fb3554c7190>
>>> 

It works \o/
