### ISSUE TITLE
Build problems; suggestions for the Readme

### ISSUE THREAD

**Issue by michael-myers** [endrazine/wcc#3]
1) Maybe you think it goes without saying but this git repo is using git submodules, so you have to pull in the other repos to the source tree:

```
git clone https://github.com/endrazine/wcc.git
cd wcc
git submodule init
git submodule update
```
2) All of these unstated dependencies had to be installed in order to build (Ubuntu 16.04) so it seems worth putting in the readme:
`sudo apt-get install clang libbfd-dev uthash-dev libelf-dev libcapstone-dev libreadline6 libreadline6-dev libiberty-dev libgsl-dev`

3) I had to add a line to wcc.c, in order to pull in the definition of a macro called PRIx64:
`#include <inttypes.h>`

**Comment by endrazine** [comment]
Good catch Michael, thanks :)

I have updated the README.md to reflect your suggested method to fetch git modules as well as provided the command line you provided to fetch C headers and dependancies on Ubuntu. Kuddos !
I am also adding the missing C header you spotted.

I have updated the README.md with example usage and an explaination of each command to get you started from there :)

Thanks a lot for beta testing this Michael, you rock !!

**Comment by michael-myers** [comment]
Thanks for releasing your work and thanks for adding all that documentation!

**Comment by endrazine** [comment]
No worries Mike. I hope it helps in getting started :))
