### ISSUE TITLE
Ubuntu build issue

### ISSUE THREAD

**Issue by joeyrideout** [endrazine/wcc#8]
After getting dependencies installed on Ubuntu 14.04 (steps [here](https://github.com/endrazine/wcc/pull/7)), `make` exits with the following warnings and errors.

The following error appears to be the only blocker:
`/home/ubuntu/wcc/src/wcc/wcc.c:2638: undefined reference to 'DL_COUNT'`

... which is odd because `utlist.h` is included in the file, which should define that macro. Could use some help debugging this! Full make output is below.

[make_output.txt](https://github.com/endrazine/wcc/files/416750/make_output.txt)

**Comment by endrazine** [comment]
Hi Joey,
Thanks for fixing the installation requirements on the Readme.md : I have merged your commit.
It seems like you're lacking utlist.h in your include path. I have added the uthash.h and utlist.h files directly within the /wcc/include/ directory, let me know if this fixes the problem on your setup :)
Cheers,
j-
